import './components/snake-header.mjs'
import './components/snake-canvas.mjs'
import './components/snake-footer-dev.mjs'
import './components/snake-app.mjs'
import './components/snake-status-box.mjs'
